let dados = [
    {
        titulo: "JavaScript: O Canivete Suíço da Web",
        descricao: "JavaScript, o canivete suíço das linguagens... só que com a lâmina enferrujada e um monte de ferramentas que você nunca pediu. É a linguagem que 'funciona' tanto no front quanto no back-end, mas com a consisciência de uma criança de cinco anos decidindo entre chocolate e brócolis.\n'Var', 'let', 'const'? Tanto faz, JavaScript vai te deixar usar qualquer coisa até quebrar seu código na pior hora possível. E claro, sempre há espaço para mais um framework novo que promete salvar o mundo, mas só vai te deixar mais confuso. Boa sorte com os callbacks infinitos!",
        link: "https://pt.wikipedia.org/wiki/JavaScript",
    },

    {
    titulo: "CSS3: O Artista Visual da Web",
    descricao: "CSS3 é aquele seu amigo que você chama pra ajudar a pintar a parede da sala, e ele chega com tinta fluorescente, grafite 3D, e um projetor pra dar 'um toque artístico'. Você pediu algo simples? Esquece! CSS3 é o cara que transforma uma reforma em uma instalação de arte contemporânea. E se você reclamar que tá exagerado, ele ainda responde: 'Ué, tá sem visão, brother? Isso aqui é style!'\nE tem o Flexbox, né? Flexbox é o Leonardo DiCaprio em A Origem: te promete um sonho dentro de outro sonho e, quando você acha que alinhou o layout, BUM, tá em outro nível, com as colunas no lugar que você nem sabia que existia. CSS3 olha pra você e fala: 'Relaxa, a gente vai chegar lá!'... mas ninguém chega!\nNo final, CSS3 é aquele diretor de cinema estilo Michael Bay: ama uma explosão. Ele transforma o site em um espetáculo de fogos de artifício e ação desnecessária, mas quando ele acerta, meu amigo, *Absolute Cinema!* O site fica bonito, funcional, e você até esquece que passou três dias tentando alinhar uma div.",
    link: "https://pt.wikipedia.org/wiki/CSS3",

    },

    {
        titulo: "C# A.K.A: C SHARP",
        descricao: "Ah, C#, a linguagem que parece ter sido criada para aqueles que acham o C++ 'muito 1990' e o Java 'muito cafona'.\nC# é tipo aquele gerente chato que ninguém aguenta, mas todo mundo precisa. Ele vai te fazer seguir cada regra, cada detalhe, te encher com burocracia de .NET e Visual Studio, mas quando você precisa que algo funcione sem explodir na cara do cliente, C# é o cara. Não importa o quão frustrado você fique tentando entender por que o código não compila (e sim, vai ser por causa de um ponto e vírgula perdido), ele vai entregar o resultado. Só que, no processo, meu amigo, você vai ficar careca, estressado, e se perguntando por que não escolheu algo mais simples como Python.",
        link: "https://pt.wikipedia.org/wiki/C_Sharp",
    },
    {
        titulo: "Ruby: A Joia da Programação",
        descricao: "Ruby, a linguagem preferida de quem quer ser 'elegante' sem perder a performance. Sim, ela é simples, flexível e uma das queridinhas para desenvolvimento web com o famoso Ruby on Rails.\nÉ como aquele amigo que consegue ser charmoso mesmo de moletom.\nMas não se engane pela sua sintaxe amigável e intuitiva; Ruby também tem seu lado 'dark'.\nEscreva um código ruim, e você vai se sentir como se estivesse tentando entender poesia abstrata.\nE claro, não vamos esquecer que o desempenho pode ser... digamos, 'relaxado' em algumas situações.",
        link: "https://pt.wikipedia.org/wiki/Ruby_(linguagem_de_programação)",
    },
    {
        titulo: "Java: O Dinossauro da Programação",
        descricao: "Ah, Java... o dinossauro da programação. Sabe aquele tio que ainda aparece nas festas de família com as mesmas piadas desde 1995, achando que tá arrasando? Esse é o Java! Ele ainda acha que portabilidade é a última grande invenção, enquanto o resto das linguagens já tá discutindo criptomoedas, IA e metaverso. Java tá lá, firme, tentando te convencer que escrever public static void main é o ápice da inovação, enquanto Python já resolveu o problema em duas linhas e saiu pra almoçar.\nQuer escrever um 'Hello World' em Java? Prepara o café! Você vai gastar mais linhas de código do que precisa pra pedir um empréstimo no banco. Enquanto a galera do Python resolve isso com duas linhas e vai viver a vida, você tá ali escrevendo public static void main como se fosse um Expecto Patronum.\n No fim das contas, Java é tipo aquela enciclopédia velha. Todo mundo tem, tá lá pegando poeira, mas foi ela que construiu o conhecimento que a galera mais nova tá usando. Quando o papo é sistema bancário, transação milionária, você acha que JavaScript ou Python tá segurando isso? Não mesmo! Java é o veterano de guerra, o cara que já viu tudo, aguentou de tudo. Tenta rodar um sistema financeiro sem ele e depois me diz quem é que manda!",
        link: "https://pt.wikipedia.org/wiki/Java_(linguagem_de_programação)",
    },
    {
        titulo: "PHP",
        descricao: "PHP é como aquela barata que você acha que matou, mas ela sempre volta!Cara, não importa o quanto você tenta se livrar dele, ele tá lá, rindo na sua cara.\nVocê acha que encontrou uma solução melhor? PHP já tá lá na sua base de código, esperando pra arruinar seu dia com um bug inesperado. HP é tipo aquele ex que você bloqueia em todas as redes sociais, mas de alguma forma, sempre acaba te mandando mensagem no LinkedIn. Ele é indestrutível, teimoso, e simplesmente não vai embora!\nEle é como aquele político que aparece em toda eleição com o mesmo discurso batido. Ele tá lá prometendo tudo: 'Vou resolver todos os seus problemas de desenvolvimento web!' Aí você vota nele porque, sei lá, pelo menos ele é familiar, e quando você vê, tá preso num ciclo de corrupção de bugs e gambiarras.\nVocê quer mudar, quer algo novo, mas adivinha só? Ele tá de volta nas eleições de 2024, com um novo slogan: 'PHP: Agora com menos vazamento de memória!' E lá vai você, votando no mesmo cara de novo, porque, afinal, ele sempre tá por aí, né? Vamos ser honestos: PHP é tipo aquela série de TV que já tá na décima temporada e ninguém sabe como ainda tá no ar. 'Friends' já acabou, 'Game of Thrones' decepcionou, mas PHP tá lá, renovado pra mais um ano. E por quê? Porque apesar de tudo, ele tem uma base fiel.\nVocê pode odiar, pode criticar, mas no fundo, sabe que ele é confiável. Enquanto as linguagens novas são tipo aquele spin-off que tenta pegar o hype, PHP é o original que você, secretamente, nunca vai deixar de assistir.",
        link: "https://pt.wikipedia.org/wiki/PHP",
    },

    {
        titulo: "Go",
        descricao: "Go, ou G.U.L.A.G, é uma linguagem de programação criada pelo Google que leva o minimalismo ao extremo.Ela é projetada para ser simples e eficiente, mas essa simplicidade pode ser limitante, fazendo com que pareça que você está tentando pintar uma obra-prima com apenas duas cores.\nAh, as “Goroutines”! Vendidas como a poção mágica que resolve todos os problemas de concorrência, mas na prática, é como tentar dirigir um ônibus escolar cheio de pinguins bêbados dançando salsa. \nVocê achou que estava contratando uma equipe de dançarinos coordenados, mas acabou com um flash mob de aves desajeitadas no meio da Avenida Paulista.\nA simplicidade prometida? É tipo aquele amigo que diz 'Deixa comigo, eu sei fazer um churrasco', e quando você vê, tá jogando pão de alho direto na brasa com o isopor junto.\nApesar de já ter mais de uma década, Go ainda é considerado jovem no mundo das linguagens de programação.Tem menos suporte da comunidade e bibliotecas disponíveis, o que pode resultar em mais trabalho para o programador.",
        link: "https://pt.wikipedia.org/wiki/Go_(linguagem_de_programação)",
    },
    {
        titulo: "TypeScript",
        descricao: "Programar em TypeScript é como ser o detetive de uma série policial ruim.  Cada variável é suspeita até que se prove o contrário, e você tem que interrogá-las uma por uma: 'Qual é o seu tipo? O que você faz aqui? Alguém pode confirmar seu alibi?'\nE mesmo depois de passar pelo inferno de papeis e burocracia, você ainda não tem a menor ideia de quem cometeu o crime ou, pior, o crime nem era tão importante assim para começar. Mas parabéns, você seguiu todos os protocolos, e nada foi resolvido.\nUsar TypeScript é como tentar aprender a Força com um Mestre Yoda que sofre de perda de memória recente. 'Declare o tipo, você deve!', ele diz, mas logo depois te joga numa selva de herança complexa e tipagem genérica. É como se você fosse Luke Skywalker tentando pegar um sabre de luz, mas acaba pegando um bastão de pesca porque o Mestre Yoda decidiu mudar as regras do treinamento no meio do caminho.\n'Salvo dos bugs, você será, mas só depois de lutar com o lado escuro das interfaces infinitas.'Grandes empresas adotam TypeScript como quem adota um novo regulamento de compliance. Parece chique, todo mundo diz que é a melhor prática, mas no fundo é só mais um monte de regras pra todo mundo seguir sem entender por quê.\nVocê entra na reunião de desenvolvimento pensando que vai criar o próximo grande produto, mas acaba discutindo por 40 minutos se aquele objeto é realmente um 'any' ou apenas um 'unknown'. Porque, no fim das contas, TypeScript é isso: uma reunião interminável que poderia ter sido um e-mail.",
        link: "https://pt.wikipedia.org/wiki/TypeScript",
    },
    {
        titulo: "HTML5: A Lenda Viva",
        descricao: "Ah, HTML5, a lenda viva. Ele aparece dizendo: 'Agora com tags semânticas e vídeos integrados!', como se isso fosse um presente divino. Mano, você basicamente pegou o que a web já fazia e deu um tapa na maquiagem. Aí ele coloca aquele sorrisinho de quem acha que revolucionou a internet.\n HTML5 é tipo o cara que chega na reforma da casa, coloca a primeira parede e depois sai pra tomar um café, deixando os outros finalizarem a obra. Mas ok, ele merece crédito por algumas coisas. O vídeo e áudio nativos são realmente úteis. Ninguém sente saudade de baixar trocentos plugins pra assistir a um vídeo.\n HTML5 deixou a internet menos irritante, e isso já é alguma coisa. E sim, o design responsivo é uma vitória. O cara até que trabalha direitinho com o CSS3 pra fazer o site funcionar em qualquer dispositivo. É aquele tipo de coisa que não faz você aplaudir de pé, mas pelo menos você pensa: 'É, ele fez o básico bem feito.'.\nEntão, no final das contas, HTML5 não é inútil, mas também não é o revolucionário que ele pensa ser.",
        link: "https://pt.wikipedia.org/wiki/HTML5",
    }   
];
